# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltexam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='beltexam.User')),
                ('wishlist_by', models.ManyToManyField(related_name='wishlist_items', to='beltexam.User')),
            ],
        ),
    ]
